# Run2 physics_params ----------------------------------------------------------
#     This rule runs the iterative procedure for FullRun2 years using RD.

rule physics_params_run2_data:
  input:
    samples = lambda wcs: tuples(wcs,mode='Bs2JpsiPhi',year='Run2'),
    # Angular acceptance
    angacc_biased = [
      'output/params/angular_acceptance/2015/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_biased.json',
      'output/params/angular_acceptance/2016/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_biased.json',
      'output/params/angular_acceptance/2017/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_biased.json',
      'output/params/angular_acceptance/2018/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_biased.json'
    ],
    angacc_unbiased = [
      'output/params/angular_acceptance/2015/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_unbiased.json',
      'output/params/angular_acceptance/2016/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_unbiased.json',
      'output/params/angular_acceptance/2017/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_unbiased.json',
      'output/params/angular_acceptance/2018/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_unbiased.json'
    ],
    # Time acceptance coefficients
    timeacc_biased = [
      'output/params/time_acceptance/2015/Bd2JpsiKstar/{version}_{timeacc}_biased.json',
      'output/params/time_acceptance/2016/Bd2JpsiKstar/{version}_{timeacc}_biased.json',
      'output/params/time_acceptance/2017/Bd2JpsiKstar/{version}_{timeacc}_biased.json',
      'output/params/time_acceptance/2018/Bd2JpsiKstar/{version}_{timeacc}_biased.json'
    ],
    timeacc_unbiased = [
      'output/params/time_acceptance/2015/Bd2JpsiKstar/{version}_{timeacc}_unbiased.json',
      'output/params/time_acceptance/2016/Bd2JpsiKstar/{version}_{timeacc}_unbiased.json',
      'output/params/time_acceptance/2017/Bd2JpsiKstar/{version}_{timeacc}_unbiased.json',
      'output/params/time_acceptance/2018/Bd2JpsiKstar/{version}_{timeacc}_unbiased.json'
    ],
    # CSP
    csp_factors = [
      'output/params/csp_factors/2015/Bs2JpsiPhi/{version}.json',
      'output/params/csp_factors/2016/Bs2JpsiPhi/{version}.json',
      'output/params/csp_factors/2017/Bs2JpsiPhi/{version}.json',
      'output/params/csp_factors/2018/Bs2JpsiPhi/{version}.json'
    ],
    # Time resolution
    time_resolution = [
      'output/params/time_resolution/2015/Bs2JpsiPhi/{version}.json',
      'output/params/time_resolution/2016/Bs2JpsiPhi/{version}.json',
      'output/params/time_resolution/2017/Bs2JpsiPhi/{version}.json',
      'output/params/time_resolution/2018/Bs2JpsiPhi/{version}.json'
    ],
    # Flavor tagging
    flavor = [
      'output/params/flavor_tagging/2015/Bs2JpsiPhi/{version}.json',
      'output/params/flavor_tagging/2016/Bs2JpsiPhi/{version}.json',
      'output/params/flavor_tagging/2017/Bs2JpsiPhi/{version}.json',
      'output/params/flavor_tagging/2018/Bs2JpsiPhi/{version}.json'
    ],
  output:
    params = 'output/params/angular_fit/run2/Bs2JpsiPhi/{version}_{angacc}_{timeacc}.json',
    tables = 'output/tables/angular_fit/run2/Bs2JpsiPhi/{version}_{angacc}_{timeacc}.tex'
  log:
    'output/log/angular_acceptance/physics_params/run2/Bs2JpsiPhi/{version}_{angacc}_{timeacc}.log'
  run:
    shell(f"""(time\
    python angular_fit/fit_test_data.py\
           --samples                 {",".join(input.samples)}\
           --angacc-biased           {",".join(input.angacc_biased)}\
           --angacc-unbiased         {",".join(input.angacc_unbiased)}\
           --timeacc-biased          {",".join(input.timeacc_biased)}\
           --timeacc-unbiased        {",".join(input.timeacc_unbiased)}\
           --csp                     {",".join(input.csp_factors)}\
           --time-resolution         {",".join(input.time_resolution)}\
           --flavor-tagging          {",".join(input.flavor)}\
           --params                  {output.params}\
           --tables                  {output.tables}\
           --year                    {",".join(yd['Run2'])}\
           --version                 {wildcards.version}\
    ) &> {log} #2>&1""")
    send_mail(f"Run2 Fit", f"{log}")








# Run2a angular acceptance -----------------------------------------------------
#     This rule runs the iterative procedure for Run2a years (2015&2016) using
#     both MC and MC_dG0 files.
rule physics_params_Run2aRepo:
  input:
    samples = lambda wcs: tuples(wcs,mode='Bs2JpsiPhi',year='Run2a'),
    # Angular acceptance
    angacc_biased = [
      'output/params/angular_acceptance/2015/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_biased.json',
      'output/params/angular_acceptance/2016/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_biased.json'
    ],
    angacc_unbiased = [
      'output/params/angular_acceptance/2015/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_unbiased.json',
      'output/params/angular_acceptance/2016/Bs2JpsiPhi/{version}_{angacc}_{timeacc}_unbiased.json'
    ],
    # Time acceptance coefficients
    timeacc_biased = [
      'output/params/time_acceptance/2015/Bd2JpsiKstar/{version}_{timeacc}_biased.json',
      'output/params/time_acceptance/2016/Bd2JpsiKstar/{version}_{timeacc}_biased.json'
    ],
    timeacc_unbiased = [
      'output/params/time_acceptance/2015/Bd2JpsiKstar/{version}_{timeacc}_unbiased.json',
      'output/params/time_acceptance/2016/Bd2JpsiKstar/{version}_{timeacc}_unbiased.json'
    ],
    # CSP
    csp_factors = [
      'output/params/csp_factors/2015/Bs2JpsiPhi/{version}.json',
      'output/params/csp_factors/2016/Bs2JpsiPhi/{version}.json'
    ],
    # Time resolution
    time_resolution = [
      'output/params/time_resolution/2015/Bs2JpsiPhi/{version}.json',
      'output/params/time_resolution/2016/Bs2JpsiPhi/{version}.json'
    ],
    # Flavor tagging
    flavor = [
      'output/params/flavor_tagging/2015/Bs2JpsiPhi/{version}.json',
      'output/params/flavor_tagging/2016/Bs2JpsiPhi/{version}.json'
    ],
  output:
    params = 'output/params/angular_fit/run2a/Bs2JpsiPhi/{version}_{angacc}_{timeacc}.json',
    tables = 'output/tables/angular_fit/run2a/Bs2JpsiPhi/{version}_{angacc}_{timeacc}.tex'
  log:
    'output/log/angular_acceptance/physics_params/run2a/Bs2JpsiPhi/{version}_{angacc}_{timeacc}.log'
  run:
    shell(f"""(time\
    python angular_fit/fit_test_data.py\
           --samples                 {",".join(input.samples)}\
           --angacc-biased           {",".join(input.angacc_biased)}\
           --angacc-unbiased         {",".join(input.angacc_unbiased)}\
           --timeacc-biased          {",".join(input.timeacc_biased)}\
           --timeacc-unbiased        {",".join(input.timeacc_unbiased)}\
           --csp                     {",".join(input.csp_factors)}\
           --time-resolution         {",".join(input.time_resolution)}\
           --flavor-tagging          {",".join(input.flavor)}\
           --params                  {output.params}\
           --tables                  {output.tables}\
           --year                    {",".join(yd['Run2a'])}\
           --version                 {wildcards.version}\
    ) &> {log} #2>&1""")
    send_mail(f"Physics Parameters Run2a", f"{log}")













# Run2a angular acceptance -----------------------------------------------------
#     This rule runs the iterative procedure for Run2a years (2015&2016) using
#     both MC and MC_dG0 files.
rule physics_params_mc:
  wildcard_constraints:
    mode = "(TOY|MC)_(Bs2JpsiPhi(_dG0)?|Bs2JpsiKK_Swave)"
  input:
    samples = lambda wcs: [tuples(wcs)],
    # CSP
    csp_factors = [
      'output/params/csp_factors/{year}/{mode}/{version}.json',
    ],
  output:
    params = 'output/params/angular_fit/{year}/{mode}/{version}_base.json',
    tables = 'output/tables/angular_fit/{year}/{mode}/{version}_base.tex'
  log:
    'output/log/angular_acceptance/physics_params_mc/{year}/{mode}/{version}.log'
  run:
    shell(f"""(time\
    python angular_fit/fit_test_mc.py\
           --samples                 {",".join(input.samples)}\
           --csp                     {",".join(input.csp_factors)}\
           --params                  {output.params}\
           --tables                  {output.tables}\
           --year                    {",".join([wildcards.year])}\
           --version                 {wildcards.version}\
    ) #&> {log} #2>&1""")
    send_mail(f"Run2a Fit", f"{log}")
