stages:
  - build
  - test

before_script:
  - echo "Hello"

job A:
  stage: build
  script:
    - mkdir -p .ccache
    - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O .ccache/miniconda.sh
    - bash .ccache/miniconda.sh -b -s -f -p .ccache/conda3
    - source .ccache/conda3/bin/activate
    - conda update -n base -c defaults conda
    - conda create --name phisscq
    - conda activate phisscq
    - conda config --add channels conda-forge
    - conda install pip pocl pyopencl
    - git clone https://gitlab.cern.ch/mromerol/ipanema3.git .ccache/ipanema3
    - pip install -e .ccache/ipanema3
    - pip install snakemake==5.22.0 hep_ml py-cpuinfo
    - cp utils/default.json config.json
    - python -c "import ipanema"

  cache:
    key: build_cache
    paths:
      - .ccache
  after_script:
    - echo "World"

job B:
  stage: test
  script:
    - ls .ccache
  cache:
    key: build_cache
    paths:
      - .ccache