# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - git clone https://gitlab.cern.ch/mromerol/ipanema3.git ipanema3/
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p conda3/
  - source conda3//bin/activate
  - conda create --name phisscq
  - conda activate phisscq
  - conda config --add channels conda-forge
  - conda install pip pocl pyopencl ROOT
  - git clone ssh://git@gitlab.cern.ch:7999/mromerol/ipanema3.git ipanema3/
  - pip install -e ipanema3/
  - pip install snakemake hep_ml py-cpuinfo
test:
  script:
    - python -c "import ipanema"


run:
  script:
    - python examples/parameters_test.py
    #- python examples/simple_fit_test.py
    #- python examples/test_cuda.py
    #- python examples/test_opencl.py
    - python examples/fit_python_test.py
