stages:
    - build
    - test



before_script:
    - echo "Before Script"
    - pwd
    - ls .ccache
    #- source .ccache/conda3/bin/activate
    #- conda activate phisscq
    - export IPANEMA_BACKEND='opencl'
    - export PYOPENCL_COMPILER_OUTPUT=1
    - export PYOPENCL_NO_CACHE=1
    - export PYTHONPATH=$PWD:$PYTHONPATH


setup_environment:
  stage: build
  before_script:
    - rm -rf .ccache
    - pwd
    - ls
  script:
    - mkdir -p sidecar
    - mkdir -p .ccache
    - git clone https://gitlab.cern.ch/mromerol/ipanema3.git .ccache/ipanema3
  cache:
    key: build-cache
    paths:
      - .ccache
  #only:
  #  changes:
  #    - utils/install.sh
  #    - utils/default.json
  #    - .gitlab-ci.yml
  #artifacts:
  #  paths:
  #    - sidecar
  #  expire_in: 1 year


job B:
  stage: test
  script:
    - ls .ccache/ipanema3
  cache:
    key: build_cache
    paths:
      - .ccache
