stages:
  - build
  - test
  - deploy
  


before_script:
  - echo "Hello"
  - ls .ccache



Setup Environment:
  stage: build
  before_script:
    - ls -larth
  script:
    - rm -rf .ccache sidecar
    - mkdir -p .ccache sidecar
    - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O .ccache/miniconda.sh
    - bash .ccache/miniconda.sh -b -s -f -p .ccache/conda3
    - source .ccache/conda3/bin/activate
    - conda update -n base -c defaults conda
    - conda create --name phisscq
    - conda activate phisscq
    - conda config --add channels conda-forge
    - conda install pip pocl pyopencl
    - git clone https://gitlab.cern.ch/mromerol/ipanema3.git .ccache/ipanema3
    - pip install -e .ccache/ipanema3
    - pip install snakemake==5.22.0 hep_ml py-cpuinfo
    - cp utils/default.json config.json
    - python -c "import ipanema"
  cache:
    key: build_cache
    paths:
      - .ccache
  only:
    changes:
      - utils/install.sh
      - utils/default.json
      - .gitlab-ci.yml
  artifacts:
    paths:
      - sidecar
    expire_in: 1 year



Test Environment:
  stage: test
  script:
    - ls .ccache
    - python -c "import ipanema"
    - python -c "from ipanema import initialize; initialize('opencl',1)"
  cache:
    key: build_cache
    paths:
      - .ccache



Test pipeline:
  stage: test
  script:
    - snakemake sidecar/2015/Bd2JpsiKstar/v0r5_sWeight.root -j -f
  artifacts:
    paths:
      - sidecar
    expire_in: 1 year
  cache:
    key: build_cache
    paths:
      - .ccache


