variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"



cache: &cache_definition
  key: build_cache
  paths:
    - miniconda
    - .cache/pip



.cache_consumer:
  cache:
    <<: *cache_definition
    policy: pull



stages:
  - setup
  - build
  - test



before_script:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - mkdir sidecar



setup_environment:
  stage: setup
  script:
    - bash miniconda.sh -b -p conda3/
    - source conda3//bin/activate
    - conda create --name phisscq
    - conda activate phisscq
    - conda config --add channels conda-forge
    - conda install pip pocl pyopencl ROOT
    - git clone https://gitlab.cern.ch/mromerol/ipanema3.git ipanema3/
    - pip install -e ipanema3/
    - pip install snakemake==5.22.0 hep_ml py-cpuinfo
    - cp utils/default.json config.json



test_environment:
  stage: test
  script:
    - python -c "import ipanema"



run:
  stage: test
  extends: .cache_consumer
  script:
    - snakemake sidecar/2015/Bd2JpsiKstar/v0r5.root -j -f
