variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"



cache: &cache_definition
  key: build_cache
  paths:
    - /builds/mromerol/conda3
    - .cache/pip
    - /builds/mromerol/sidecar



.cache_consumer:
  cache:
    <<: *cache_definition
    policy: pull



stages:
  - setup
  - test
  - run


default:
  before_script:
    - pwd
    - ls
    - source /builds/mromerol/conda3/bin/activate
    - conda activate phisscq
    - export IPANEMA_BACKEND='opencl'
    - export PYOPENCL_COMPILER_OUTPUT=1
    - export PYOPENCL_NO_CACHE=1
    - export PYTHONPATH="phis-scq":$PYTHONPATH
    - ls /builds/mromerol/


setup_environment:
  stage: setup
  before_script:
    - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - mkdir -p /builds/mromerol/sidecar
    - pwd
    - ls /builds/mromerol/
  script:
    - bash miniconda.sh -b -s -f -p /builds/mromerol/conda3/
    - source /builds/mromerol/conda3/bin/activate
    - conda update -n base -c defaults conda
    - conda create --name phisscq
    - conda activate phisscq
    - conda config --add channels conda-forge
    - conda install pip pocl pyopencl ROOT
    - git clone https://gitlab.cern.ch/mromerol/ipanema3.git /builds/mromerol/ipanema3/
    - pip install -e /builds/mromerol/ipanema3/
    - pip install snakemake==5.22.0 hep_ml py-cpuinfo
    - cp utils/default.json config.json
    - python -c "import ipanema"
  only:
    changes:
      - utils/install.sh
      - utils/default.json
      - .gitlab-ci.yml




test_environment:
  stage: test
  extends: .cache_consumer
  script:
    - python -c "import ipanema"
    - python -c "from ipanema import initialize; initialize('opencl',1)"



test_snakemake:
  stage: test
  extends: .cache_consumer
  script:
    - snakemake /builds/mromerol/sidecar/2015/Bd2JpsiKstar/v0r5_sWeight.root -j -f


run:
  stage: run
  extends: .cache_consumer
  script:
    - snakemake /builds/mromerol/sidecar/2015/Bd2JpsiKstar/v0r5.root -j -f
