stages:
  - build
  - test

before_script:
  - echo "Hello"

job A:
  stage: build
  script:
    - mkdir -p .ccache
    - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O .ccache/miniconda.sh
  cache:
    key: build_cache
    paths:
      - .ccache
  after_script:
    - echo "World"

job B:
  stage: test
  script:
    - cat .ccache/miniconda.sh
  cache:
    key: build_cache
    paths:
      - .ccache