# Set of rules to run and apply GB weighting
#


# preliminar selection before GB {{{

rule selection_gbw_preliminar_mc:
    """
    Rule for selecting MC for GB weights.
    Apply cuts specified in input yaml files on the given tree and adds branches
    specified in the corresponding yaml file. Saves new tree in the requested location
    """
    threads: 4
    resources:
        mem_mb =  6000
    wildcard_constraints:
        mode = "MC_(Bs2JpsiPhi|Bd2JpsiKstar|Bu2JpsiKplus)(_dG0)?"
    input:
        script = 'selection/tools/apply_selection.py',
        #file = expand(rules.merge_polarities.output, mode='{mode}',
        #                                              year='{year}',
        #                                              strip_sim='{strip_sim}'),
        cuts = ['selection/cuts.yaml', 'selection/gb_weights/cuts.yaml'],
        branches = 'selection/branches.yaml',
        file = SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_pidcorrected.root',
    output:
        # temp(tuples_path('{mode}/{mode}_{strip_sim}_{year}_GBW_MC_selected.root'))
        SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_preliminarGBW.root',
        # /scratch46/marcos.romero/sidecar14/{year}/{mode}/{version}_{strip_sim}GBWpreliminar.root'
    params:
        cutkeys = 'B_TAU_cuts L0_cuts HLT1_cuts HLT2_cuts MC_specific',
        # file = lambda wildcards: selconfig['eos'] + '/' + config['version'] + '/PID/{}/{}_{}_{}_selected_pidcorrected.root'.format(wildcards.mode, wildcards.mode, wildcards.year, wildcards.strip_sim)
    log:
        'output/log/select_GBW_MC_ntuples/{mode}/{version}_{strip_sim}_{year}_GBW_MC_selected.log'
    run:
        shell(f'(time python {input.script} --input-file {input.file} \
                               --output-file {output} \
                               --mode {wildcards.mode} \
                               --cut-keys {params.cutkeys} \
                               --selection-files {input.cuts} \
                               --branches-files {input.branches} \
                               --year {wildcards.year}) &> {log}')


rule selection_gbw_preliminar_data:
    """
    Rule for sweighting data for GB weights.
    Apply cuts specified in input yaml files on the given tree and adds branches
    specified in the corresponding yaml file. Saves new tree in the requested location
    """
    threads: 4
    resources:
        mem_mb = 6000
    wildcard_constraints:
        mode = "(Bs2JpsiPhi|Bd2JpsiKstar|Bu2JpsiKplus)"
    input:
        script = 'selection/tools/apply_selection.py',
        cuts = ['selection/cuts.yaml', 'selection/gb_weights/cuts.yaml'],
        branches = ['selection/gb_weights/branches.yaml', 'selection/gb_weights/weighting_variables.yaml']
    output:
        # temp(tuples_path('{mode}/{mode}_{year}_GBW_data_selected.root'))
        SAMPLES + '/{year}/{mode}/{version}_preliminarGBW.root'
    params:
        files = lambda wildcards: selconfig['eos_mc'][wildcards.mode][int(wildcards.year)][wildcards.strip_sim] \
                if wildcards.mode.startswith('MC_') \
                else selconfig['eos_data'][selconfig['streams'][wildcards.mode]][int(wildcards.year)],
        treename = lambda wildcards: selconfig['treenames'][wildcards.mode],
        cutkeys = 'B_TAU_cuts L0_cuts HLT1_cuts HLT2_cuts B_cuts_SW_GBW'
    log:
        'output/log/select_GBW_data_ntuples/{year}/{mode}/{version}_GBW_MC_selected.log'
    run:
        shell(f'(time python {input.script} \
        --input-file {params.files} \
        --input-tree-name {params.treename} \
        --output-file {output} \
        --mode {wildcards.mode} \
        --cut-keys {params.cutkeys} \
        --selection-files {input.cuts} \
        --branches-files {input.branches} \
        --year {wildcards.year}) &> {log}')

# }}}


# sweigting for GB weighting {{{

rule selection_gbw_bkgsubtract_data:
    """
    Rule for sweighting data for GB weights.
    Performs fit to Bs mass. Saves new tree with sweights in the requested location
    """
    threads: 2
    resources:
        mem_mb = 12000
    wildcard_constraints:
        # mode = "(Bs2JpsiPhi|Bs2JpsiPhi_Prompt)"    # ORIGINAL
        mode = "(Bs2JpsiPhi|Bs2JpsiPhi_Prompt|Bd2JpsiKstar|Bu2JpsiKplus)"
    input:
        tuple_file = SAMPLES + '/{year}/{mode}/{version}_preliminarGBW.root'
        # tuple_file = expand(rules.select_GBW_data_ntuples.output,
        #                     year='{year}', version='{version}', mode='{mode}'),
    params:
        script = 'selection/gb_weights/sweights_for_gb_weights.py',
        branch_name = 'B_ConstJpsi_M_1',
    output:
        # temp(tuples_path('{mode}/{mode}_{year}_GBW_data_sweighted.root'))
        sample = SAMPLES + '/{year}/{mode}/{version}_bkgsubtracted.root',
        plots = directory(SAMPLES + '/{year}/{mode}/{version}_bkgsubtracted/')
    log:
        # temp(tuples_path('{mode}/{mode}_{year}_GBW_data_sweighted.root'))
        'output/selection_data_background_subtraction/{year}/{mode}/{version}.log',
    run:
        shell('mkdir -p {output.plots}')
        shell('(time python {params.script} \
        --input-file {input.tuple_file} \
        --output-file {output.sample} \
        --input-branch {params.branch_name} \
        --plot-dir {output.plots} \
        --mode {wildcards.mode} \
        --year {wildcards.year}) &> {log}')


# NOT USE IPATIA rule mass_prefit_GBW_mc:
# NOT USE IPATIA     """
# NOT USE IPATIA     Run mass fit on selected Bu->J/psiKplus or Bd->J/psiKstar MC to determine Ipatia tail parameters for
# NOT USE IPATIA     the fit to data. It only takes B_BKGCAT=0,50 candidates.
# NOT USE IPATIA     """
# NOT USE IPATIA     threads: 2
# NOT USE IPATIA     resources:
# NOT USE IPATIA         mem_mb = 12000
# NOT USE IPATIA     input:
# NOT USE IPATIA         script = 'selection/tools/mass_fit_ipatia.py',
# NOT USE IPATIA         root_file =  expand(rules.select_GBW_MC_ntuples.output,
# NOT USE IPATIA                             mode ='MC_{mode}', year ='{year}',
# NOT USE IPATIA                             version ='{version}', strip_sim ='{strip_sim}')
# NOT USE IPATIA     output:
# NOT USE IPATIA         params_file =  output_path('MC_{mode}/mass_prefit_GBW_{year}/mass_fit_params_{version}_{year}_{strip_sim}.json'),
# NOT USE IPATIA         plots = directory(output_path('MC_{mode}/mass_prefit_GBW_{version}_{year}_{strip_sim}/plots/'))
# NOT USE IPATIA     shell:
# NOT USE IPATIA         'python {input.script} --input-file {input.root_file} \
# NOT USE IPATIA                                --fit-result-file {output.params_file} \
# NOT USE IPATIA                                --mode {wildcards.mode} \
# NOT USE IPATIA                                --plots-loc {output.plots}'
# NOT USE IPATIA 
# NOT USE IPATIA 
# NOT USE IPATIA 
# NOT USE IPATIA rule sweight_GBW_data_ntuple_Ipatia:
# NOT USE IPATIA     """
# NOT USE IPATIA     Rule for sweighting data for GB weights.
# NOT USE IPATIA     Performs fit to Bu or Bd mass fixing Ipatia tail parameters to mc with B_BKGCAT=0,50. 
# NOT USE IPATIA     Saves new tree with sweights in the requested location
# NOT USE IPATIA     """
# NOT USE IPATIA     threads: 2
# NOT USE IPATIA     resources:
# NOT USE IPATIA         mem_mb = 12000
# NOT USE IPATIA     input:
# NOT USE IPATIA         script = 'selection/tools/mass_fit_ipatia.py',
# NOT USE IPATIA         root_file = expand(rules.select_GBW_data_ntuples.output, mode='{mode}',version='{version}',year='{year}'),
# NOT USE IPATIA         params_file = lambda wildcards: expand(rules.mass_prefit_GBW_mc.output.params_file, version='{version}', year='{year}', mode= '{mode}', strip_sim = selconfig['gbw_input_MC_mode']['MC_'+ wildcards.mode][wildcards.year]['strip_sim'])
# NOT USE IPATIA     output:
# NOT USE IPATIA         root_file = tuples_path('{mode}/{version}_{mode}_{year}_GBW_data_sweighted_ipatia.root'),
# NOT USE IPATIA         plots = directory(output_path('{mode}/{version}_mass_fit_GBW_{year}/plots/')),
# NOT USE IPATIA         params_file = output_path('{mode}/{version}_mass_fit_GBW_{year}/mass_fit_params_{year}.json'),
# NOT USE IPATIA         root_file_tmp = temp(output_path('{mode}/{version}_mass_fit_GBW_{year}.root'))
# NOT USE IPATIA     params:
# NOT USE IPATIA         params_to_fix = ['alpha1', 'alpha2', 'n1', 'n2', 'm_sig_lambda'],
# NOT USE IPATIA         mass_range = lambda wildcards:  (5240, 5320) if('Bu' in wildcards.mode) else (5230, 5330)
# NOT USE IPATIA     shell:
# NOT USE IPATIA         'python {input.script} --input-file {input.root_file} \
# NOT USE IPATIA                                --output-file-tmp {output.root_file_tmp} \
# NOT USE IPATIA                                --output-file {output.root_file} \
# NOT USE IPATIA                                --mode {wildcards.mode} \
# NOT USE IPATIA                                --mass-range {params.mass_range} \
# NOT USE IPATIA                                --params-to-fix-file {input.params_file} \
# NOT USE IPATIA                                --params-to-fix-list {params.params_to_fix} \
# NOT USE IPATIA                                --background \
# NOT USE IPATIA                                --fit-result-file {output.params_file} \
# NOT USE IPATIA                                --plots-loc {output.plots} \
# NOT USE IPATIA                                --add-sweights'

def sweighted_data_for_gb_weights(wildcards):
    """
    TODO: change this function
    """
    # mode = wildcards.data_mode
    # version = wildcards.version
    # if wildcards.data_mode == 'Bs2JpsiPhi_Prompt':
    #     return expand(rules.select_GBW_data_ntuples.output, year=wildcards.data_year, version=version, mode=wildcards.data_mode)
    #
    # elif ('Bs2JpsiPhi' in wildcards.data_mode and wildcards.data_mode != 'Bs2JpsiPhi_Prompt'):
    #     return expand(rules.sweight_GBW_data_ntuples.output.sample, mode=wildcards.data_mode, version=version, year=wildcards.data_year)
    #
    # else:
    #     # WARNING: Now we use DSCB instead of Hypatia
    #     return expand(rules.sweight_GBW_data_ntuples.output.sample, mode=wildcards.data_mode, version=version, year=wildcards.data_year)
    #     # return expand(rules.sweight_GBW_data_ntuple_Ipatia.output.root_file,mode=wildcards.data_mode, version=version, year=wildcards.data_year) 

    return SAMPLES + f'/{wildcards.year}/{wildcards.mode}/{wildcards.version}_bkgsubtracted.root',
# }}}


# calculate GB weights {{{

rule selection_gbw_reweighter_train:
    """
    Rule to calculate GB weights on MC using sweighted data.

    """
    threads: 2
    resources:
        mem_mb = 12000
    input:
        # data = sweighted_data_for_gb_weights,
        data = SAMPLES + '/{data_year}/{data_mode}/{version}_bkgsubtracted.root',
        mc = SAMPLES + '/{mc_year}/{mc_mode}/{version}_{strip_sim}_preliminarGBW.root',
    params:
        script = 'selection/tools/reweighting.py',
        variables_file = 'selection/gb_weights/weighting_variables.yaml',
        target_weight = lambda wildcards: 'sw' if wildcards.data_mode != 'Bs2JpsiPhi_Prompt' else '1',
        weight_method = 'gb'
    output:
        # tuples_path('{mc_mode}/{mc_year}/{strip_sim}/{mc_mode}_{mc_year}_{strip_sim}_{data_mode}_{data_year}_GB_weights.pkl'),
        SAMPLES + '/{mc_year}/{mc_mode}/{version}_{strip_sim}_gbWeighted_{data_mode}_{data_year}.pkl'
    log:
        'output/log/selection_calculate_gbw/{mc_mode}/{mc_year}/{strip_sim}/{version}_{mc_mode}_{mc_year}_{strip_sim}_{data_mode}_{data_year}_GB_weights.log'
    run:
        shell('(time python {params.script} \
        --original-file {input.mc} \
        --target-file {input.data} \
        --target-weight {params.target_weight} \
        --mode {wildcards.mc_mode} \
        --weight-method {params.weight_method} \
        --variables-files {params.variables_file} \
        --output-file {output}) &> {log}')

# }}}


# apply GB weights {{{

# TODO: cargarselo
# def weights_for_GBW(wildcards):
#     mc_mode = selconfig['gbw_input_MC_mode'][wildcards.mode][wildcards.year]['mode']
#     strip_sim = selconfig['gbw_input_MC_mode'][wildcards.mode][wildcards.year]['strip_sim']
#     mc_year = selconfig['gbw_input_MC_year'][wildcards.year]
#     data_mode = selconfig['gbw_input_data_mode'][wildcards.mode]
#     data_year = selconfig['gbw_input_data_year'][wildcards.year]
#
#     return expand(rules.selection_pkl_gb_weights.output, mc_mode=mc_mode,
#                                                      mc_year=mc_year,
#                                                      version=wildcards.version,
#                                                      data_mode=data_mode,
#                                                      data_year=data_year,
#                                                      strip_sim=strip_sim)


#Rescaling Veronika
def trackchi2_vars(wildcards):
    mode = wildcards.mode
    if wildcards.mode == 'MC_Bu2JpsiKplus':
        return '{"hplus_TRACK_CHI2NDOF", "muplus_TRACK_CHI2NDOF", "muminus_TRACK_CHI2NDOF"}'
    else:
        return '{"hplus_TRACK_CHI2NDOF", "hminus_TRACK_CHI2NDOF", "muplus_TRACK_CHI2NDOF", "muminus_TRACK_CHI2NDOF"}'


rule selection_apply_trackchi2_scaling:
    """
    Rule to rescale TrackChi2 variables on MC using sweighted data.
    """
    threads: 2
    resources:
        mem_mb = 12000
    input:
        input_mc = SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_beforeGBW.root',
        input_data =  lambda wcs: expand(
                SAMPLES + '/{data_year}/{data_mode}/{version}_bkgsubtracted.root',
                version = wcs.version,
                data_mode = selconfig['gbw_input_data_mode'][f'{wcs.mode}'],
                data_year = selconfig['gbw_input_data_year'][f'{wcs.year}']
                )

    params:
        target_weight = lambda wildcards: expand('\"sw\"' if selconfig['gbw_input_data_mode'][wildcards.mode] != 'Bs2JpsiPhi_Prompt'
                                                      else '\"\"'),
        treename = "DecayTree",
        vars = trackchi2_vars,
	    plots = SAMPLES+ 'output/figures/plots/{mode}/{year}/TrackChi2Scaling_{strip_sim}'
    output:
        file = SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_TrackChi2_weighted.root'
    shell:
        "root -l -q 'selection/gb_weights/TrackChi2Rescaling.C({params.vars}, {params.target_weight}, \"{input.input_mc}\", \"{input.input_data}\", \"{output.file}\", \"{params.treename}\", \"{params.treename}\", \"{params.plots}\")'"






rule selection_gbw_compute:
    """
    Rule to apply GB weights on MC reading from a pickle file where these have been stored.
    """
    threads: 2
    resources:
        mem_mb = 12000
    input:
        # files = SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_beforeGBW.root',
        files = SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_TrackChi2_weighted.root',
        # TODO: checkear que esto esta bien:
        weights_file = lambda wcs: expand(
                SAMPLES + '/{mc_year}/{mc_mode}/{version}_{strip_sim}_gbWeighted_{data_mode}_{data_year}.pkl',
                mc_mode = f'{wcs.mode}',
                mc_year= f'{wcs.year}',
                strip_sim = f'{wcs.strip_sim}',
                version = f'{wcs.version}',
                data_mode = selconfig['gbw_input_data_mode'][f'{wcs.mode}'],
                data_year = selconfig['gbw_input_data_year'][f'{wcs.year}'])
    output:
        # temp(tuples_path('{mode}/{year}/{strip_sim}/{mode}_{year}_{strip_sim}_GB_weighted.root'))
        SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_gbWeight.root'
    params:
        script = 'selection/tools/apply_weights.py',
        variables_file = 'selection/gb_weights/weighting_variables.yaml',
        weight_method = 'gb',
        output_weight_name = 'gb_weights'
    log:
        'output/log/selection_calculate_gb_weights/{year}/{mode}/{version}_{strip_sim}_gbWeight.log'
    run:
        shell('(time python {params.script} \
        --input-file {input.files} \
        --variables-files {params.variables_file} \
        --weight-method {params.weight_method} \
        --weights-file {input.weights_file} \
        --mode {wildcards.mode} \
        --output-file {output} \
        --output-weight-name {params.output_weight_name}) &> {log}')


rule selection_gbw_compute_prompt:
    """
    Rule to apply GB weights on MC reading from a pickle file where these have been stored.
    For MC_Bs2JpsiPhi_Prompt weighted to Bs2JpsiPhi_Prompt data only
    """
    wildcard_constraints:
        mode = "MC_Bs2JpsiPhi_Prompt"
    threads: 2
    resources:
        mem_mb = 12000
    input:
        files = SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_gbWeight.root',
        weights_file = lambda wcs: expand(
                SAMPLES + '/{mc_year}/{mc_mode}/{version}_{strip_sim}_gbWeighted_{data_mode}_{data_year}.pkl',
                mc_mode = f'{wcs.mode}',
                strip_sim = f'{wcs.strip_sim}',
                version = f'{wcs.version}',
                mc_year= f'{wcs.year}',
                data_mode='Bs2JpsiPhi_Prompt',
                data_year = selconfig['gbw_input_data_year'][f'{wcs.year}'])
    output:
        SAMPLES + '/{year}/{mode}/{version}_{strip_sim}_gbWeight.root'
    params:
        script = 'selection/tools/apply_weights.py',
        variables_file = 'gb_weights/weighting_variables.yaml',
        weight_method = 'gb',
        output_weight_name = 'gb_weights_prompt'
    log:
        'output/log/selection_calculate_gb_weights_prompt/{year}/{mode}/{version}_{strip_sim}_gbWeight.log'
    run:
        shell('(time python {params.script} \
        --input-file {input.files} \
        --variables-files {params.variables_file} \
        --weight-method {params.weight_method} \
        --weights-file {input.weights_file} \
        --mode {wildcards.mode} \
        --output-file {output} \
        --output-weight-name {params.output_weight_name}) &> {log}')

# }}}


# vim: fdm=marker:cc=120
