
# decay_time_acceptance computations -------------------------------------------
#    These are several rules related to decay-time acceptance. The main one is
#    time_acceptance, which computes the spline coefficients of the
#    Bs2JpsiPhi acceptance.


rule single_time_acceptance:
  wildcard_constraints:
    trigger = "(biased|unbiased|combined)",
  input:
    sample = lambda wcs: tuples(wcs, mode=wcs.mode),
  params:
    params = 'time_acceptance/params/{year}/{mode}/baseline.json',
  output:
    params   = 'output/params/time_acceptance/{year}/{mode}/{version}_single_{trigger}.json',
    tables   = 'output/tables/time_acceptance/{year}/{mode}/{version}_single_{trigger}.tex',
  log:
    'output/log/time_acceptance/single_time_acceptance/{year}/{mode}/{version}_{trigger}.log'
  run:
    shell(f"""
    (time\
    python time_acceptance/single.py\
           --sample {input.sample}\
           --input-params {params.params}\
           --output-params {output.params}\
           --output-tables {output.tables}\
           --mode {wildcards.mode}\
           --year {wildcards.year}\
           --version {wildcards.version}\
           --trigger {wildcards.trigger}\
    ) &> {log} 2>&1
    """)
    send_mail("Single Time Acceptance", f"{log}")


rule simultaneous_time_acceptance:
  wildcard_constraints:
    timeacc = "(base|nonkin|9knots|12knots)(Bin)?(pt|sigmat|eta)?(1|2|3|4)?(Minos|BFGS|LBFGSB|CG|Nelder)?",
    trigger = "(biased|unbiased|combined)",
    version = "(v[1-9]r[0-9]|v0r[2-9])", # v0r0 not allowed
  input:
    sample_BsMC = lambda wcs: tuples(wcs,mode='MC_Bs2JpsiPhi_dG0'),
    sample_BdMC = lambda wcs: tuples(wcs,mode='MC_Bd2JpsiKstar'),
    sample_BdDT = lambda wcs: tuples(wcs,mode='Bd2JpsiKstar'),
  params:
    params_BsMC = 'time_acceptance/params/{year}/MC_Bs2JpsiPhi_dG0/baseline.json',
    params_BdMC = 'time_acceptance/params/{year}/MC_Bd2JpsiKstar/baseline.json',
    params_BdDT = 'time_acceptance/params/{year}/Bd2JpsiKstar/baseline.json'
  output:
    params_BsMC   = 'output/params/time_acceptance/{year}/MC_Bs2JpsiPhi_dG0/{version}_{timeacc}_{trigger}.json',
    params_BdMC   = 'output/params/time_acceptance/{year}/MC_Bd2JpsiKstar/{version}_{timeacc}_{trigger}.json',
    params_BdDT   = 'output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_{timeacc}_{trigger}.json',
    tables_BsMC   = 'output/tables/time_acceptance/{year}/MC_Bs2JpsiPhi_dG0/{version}_{timeacc}_{trigger}.tex',
    tables_BdMC   = 'output/tables/time_acceptance/{year}/MC_Bd2JpsiKstar/{version}_{timeacc}_{trigger}.tex',
    tables_BdDT   = 'output/tables/time_acceptance/{year}/Bd2JpsiKstar/{version}_{timeacc}_{trigger}.tex',
  log:
    'output/log/time_acceptance/simultaneous_time_acceptance/{year}/{version}_{timeacc}_{trigger}.log'
  run:
    shell(f"""
    (time\
    python time_acceptance/simultaneous.py\
           --BsMC-sample {input.sample_BsMC}\
           --BdMC-sample {input.sample_BdMC}\
           --BdDT-sample {input.sample_BdDT}\
           --BsMC-input-params {params.params_BsMC}\
           --BdMC-input-params {params.params_BdMC}\
           --BdDT-input-params {params.params_BdDT}\
           --BsMC-output-params {output.params_BsMC}\
           --BdMC-output-params {output.params_BdMC}\
           --BdDT-output-params {output.params_BdDT}\
           --BsMC-output-tables {output.tables_BsMC}\
           --BdMC-output-tables {output.tables_BdMC}\
           --BdDT-output-tables {output.tables_BdDT}\
           --mode Bd2JpsiKstar\
           --year {wildcards.year}\
           --version {wildcards.version}\
           --trigger {wildcards.trigger}\
           --script {wildcards.timeacc}\
    ) &> {log} 2>&1
    """)
    send_mail(f"Simultaneous Time Acceptance", f"{log}")



# decay_time_acceptance plots --------------------------------------------------
#    These are several rules related to decay-time acceptance. The main one is
#    time_acceptance, which computes the spline coefficients of the
#    Bs2JpsiPhi acceptance.


rule plot_time_acceptance:
  wildcard_constraints:
    timeacc = "(single|base|nonkin|9knots|12knots)(Minos|BFGS|LBFGSB|CG|Nelder)?",
    trigger = "(biased|unbiased|combined)"
  input:
    sample_BsMC = lambda wcs: tuples(wcs,mode='MC_Bs2JpsiPhi_dG0'),
    sample_BdMC = lambda wcs: tuples(wcs,mode='MC_Bd2JpsiKstar'),
    sample_BdDT = lambda wcs: tuples(wcs,mode='Bd2JpsiKstar'),
    params_BsMC = 'output/params/time_acceptance/{year}/MC_Bs2JpsiPhi_dG0/{version}_{timeacc}_{trigger}.json',
    params_BdMC = 'output/params/time_acceptance/{year}/MC_Bd2JpsiKstar/{version}_{timeacc}_{trigger}.json',
    params_BdDT = 'output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_{timeacc}_{trigger}.json'
  output:
    'output/params/time_acceptance/{year}/{mode}/{version}_{timeacc}_{trigger}_{plot}.pdf',
  log:
    'output/log/time_acceptance/plot_time_acceptance/{year}_{mode}_{version}_{timeacc}_{trigger}_{plot}.log'
  run:
    1+1
