
# decay_time_acceptance computations -------------------------------------------
#    These are several rules related to decay-time acceptance. The main one is
#    time_acceptance, which computes the spline coefficients of the
#    Bs2JpsiPhi acceptance.

ruleorder: single_time_acceptance > simultaneous_time_acceptance


rule single_time_acceptance:
  wildcard_constraints:
    trigger = "(biased|unbiased|combined)",
  input:
    sample = lambda wcs: tuples(wcs, mode=wcs.mode),
  params:
    params = 'time_acceptance/params/{year}/{mode}/baseline.json',
  output:
    params   = 'output/params/time_acceptance/{year}/{mode}/{version}_Single_{trigger}.json',
    tables   = 'output/tables/time_acceptance/{year}/{mode}/{version}_Single_{trigger}.tex',
  log:
    'output/log/time_acceptance/single_time_acceptance/{year}_{mode}_{version}_{trigger}.log'
  run:
    shell(f"""
    (time\
    python time_acceptance/single.py\
           --sample {input.sample}\
           --input-params {params.params}\
           --output-params {output.params}\
           --output-tables {output.tables}\
           --mode {wildcards.mode}\
           --year {wildcards.year}\
           --version {wildcards.version}\
           --trigger {wildcards.trigger}\
    ) #&> {log} #2>&1
    """)
    send_mail("Single Time Acceptance", f"{log}")


rule simultaneous_time_acceptance:
  wildcard_constraints:
    script = "(Baseline|Nonkinweighted|Nineknots|Twelveknots)(Minos|BFGS|LBFGSB|CG|Nelder)?",
    trigger = "(biased|unbiased|combined)",
    year = "(2015|2016|2017|2018)",
  input:
    sample_BsMC = lambda wcs: tuples(wcs,mode='MC_Bs2JpsiPhi_dG0'),
    sample_BdMC = lambda wcs: tuples(wcs,mode='MC_Bd2JpsiKstar'),
    sample_BdDT = lambda wcs: tuples(wcs,mode='Bd2JpsiKstar'),
    params_BsMC = 'output/params/time_acceptance/{year}/MC_Bs2JpsiPhi_dG0/{version}_Single_{trigger}.json',
    params_BdMC = 'output/params/time_acceptance/{year}/MC_Bd2JpsiKstar/{version}_Single_{trigger}.json',
    params_BdDT = 'output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_Single_{trigger}.json'
  output:
    params_BsMC   = 'output/params/time_acceptance/{year}/MC_Bs2JpsiPhi_dG0/{version}_{script}_{trigger}.json',
    params_BdMC   = 'output/params/time_acceptance/{year}/MC_Bd2JpsiKstar/{version}_{script}_{trigger}.json',
    params_BdDT   = 'output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_{script}_{trigger}.json',
    tables_BsMC   = 'output/tables/time_acceptance/{year}/MC_Bs2JpsiPhi_dG0/{version}_{script}_{trigger}.tex',
    tables_BdMC   = 'output/tables/time_acceptance/{year}/MC_Bd2JpsiKstar/{version}_{script}_{trigger}.tex',
    tables_BdDT   = 'output/tables/time_acceptance/{year}/Bd2JpsiKstar/{version}_{script}_{trigger}.tex',
  log:
    'output/log/time_acceptance/simultaneous_time_acceptance/{year}_{version}_{script}_{trigger}.log'
  run:
    shell(f"""
    (time\
    python time_acceptance/simultaneous.py\
           --BsMC-sample {input.sample_BsMC}\
           --BdMC-sample {input.sample_BdMC}\
           --BdDT-sample {input.sample_BdDT}\
           --BsMC-input-params {input.params_BsMC}\
           --BdMC-input-params {input.params_BdMC}\
           --BdDT-input-params {input.params_BdDT}\
           --BsMC-output-params {output.params_BsMC}\
           --BdMC-output-params {output.params_BdMC}\
           --BdDT-output-params {output.params_BdDT}\
           --BsMC-output-tables {output.tables_BsMC}\
           --BdMC-output-tables {output.tables_BdMC}\
           --BdDT-output-tables {output.tables_BdDT}\
           --mode Bd2JpsiKstar\
           --year {wildcards.year}\
           --version {wildcards.version}\
           --trigger {wildcards.trigger}\
           --script {wildcards.script}\
    ) &> {log} #2>&1
    """)
    send_mail(f"Simultaneous Time Acceptance", f"{log}")



# decay_time_acceptance plots --------------------------------------------------
#    These are several rules related to decay-time acceptance. The main one is
#    time_acceptance, which computes the spline coefficients of the
#    Bs2JpsiPhi acceptance.


rule plot_time_acceptance:
  wildcard_constraints:
    script = "(Single|Baseline|Nonkinweighted|Nineknots|Twelveknots)(Minos|BFGS|LBFGSB|CG|Nelder)?",
    trigger = "(biased|unbiased|combined)",
    year = "(2015|2016|2017|2018)",
  input:
    sample_BsMC = lambda wcs: tuples(wcs,mode='MC_Bs2JpsiPhi_dG0'),
    sample_BdMC = lambda wcs: tuples(wcs,mode='MC_Bd2JpsiKstar'),
    sample_BdDT = lambda wcs: tuples(wcs,mode='Bd2JpsiKstar'),
    params_BsMC = 'output/params/time_acceptance/{year}/MC_Bs2JpsiPhi_dG0/{version}_{script}_{trigger}.json',
    params_BdMC = 'output/params/time_acceptance/{year}/MC_Bd2JpsiKstar/{version}_{script}_{trigger}.json',
    params_BdDT = 'output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_{script}_{trigger}.json'
  output:
    'output/params/time_acceptance/{year}/{mode}/{version}_{script}_{trigger}_{plot}.pdf',
  log:
    'output/log/time_acceptance/plot_time_acceptance/{year}_{mode}_{version}_{script}_{trigger}_{plot}.log'
  run:
    1+1
