name: phisscq
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pocl
  - pyopencl
  - ROOT
  - root_pandas
  - hep_ml
  - iminuit 1.5.2
  - matplotlib
  - corner
  - tqdm
  - reikna
  - py-cpuinfo
  - uproot3
  - numpy
  - scipy
  - uncertainties
  - numdifftools
  - emcee
