

def find_flags(v):
  all_flags = []
  all_files = [os.path.join(dp, f) for dp, dn, fn in os.walk(os.path.expanduser(f"{SAMPLES_PATH}")) for f in fn]
  print
  for file in all_files:
    filename = os.path.splitext(os.path.basename(file))[0]
    all_flags.append(filename.split('_')[0])
  all_flags = list(dict.fromkeys(all_flags)) # remove duplicates
  return all_flags




# TODO:
# Rename some files to avout this rule ordering
ruleorder: parse_fulljson > get_csp_from_git
ruleorder: parse_fulljson > get_resolution_from_git
ruleorder: parse_fulljson > get_flavor_from_git

# this rule must be moved elsewhere at some point
#     Donwload fit_inputs_{year} from the repository to tmp folder
rule download_fulljson:
  wildcard_constraints:
    version = "(v[1-9]r[0-9]|v0r[2-9])",                      # v0r0 not allowed
  output:
    temp("tmp/{version}/fit_inputs_{year}.json")
  run:
    from bundle.parse_full_json import download_fulljson
    download_fulljson(f"{wildcards.version}", f"{wildcards.year}")


# this rule must be moved elsewhere at some point
#     Get fulljson file and parse it to work with phis-scq
rule parse_fulljson:
  wildcard_constraints:
    version = "(v[1-9]r[0-9]|v0r[2-9])",                      # v0r0 not allowed
  input:
    "tmp/{version}/fit_inputs_{year}.json"
  output:
    timeacc_biased = "output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_repo_biased.json",
    timeacc_unbiased = "output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_repo_unbiased.json",
    angacc_biased = "output/params/angular_acceptance/{year}/Bs2JpsiPhi/{version}_repo_repo_biased.json",
    angacc_unbiased = "output/params/angular_acceptance/{year}/Bs2JpsiPhi/{version}_repo_repo_unbiased.json",
    flavor = "output/params/flavor_tagging/{year}/Bs2JpsiPhi/{version}.json",
    resolution = "output/params/time_resolution/{year}/Bs2JpsiPhi/{version}.json",
    csp_factors = "output/params/csp_factors/{year}/Bs2JpsiPhi/{version}.json"
  run:
    from bundle.parse_full_json import parse_fulljson
    # parse
    tb, tu, ab, au, res, flavor, csp = parse_fulljson(f"{input}")
    # dump
    tb.dump(f"{output.timeacc_biased}")
    tu.dump(f"{output.timeacc_unbiased}")
    ab.dump(f"{output.angacc_biased}")
    au.dump(f"{output.angacc_unbiased}")
    res.dump(f"{output.resolution}")
    flavor.dump(f"{output.flavor}")
    csp.dump(f"{output.csp_factors}")

# -----------------------------------------------------
# -----------------------------------------------------
# -----------------------------------------------------
# -----------------------------------------------------






















rule figures_bundle:
  wildcard_constraints:
    version = "(v[1-9]r[0-9]|v0r[2-9])"  # v0r0 and v0r2 (2015&2016) not allowed
  input:
    # Reweightings figures
    rwp1 = expand(rules.plot_time_acceptance_reweightings.output,
                  version='{version}',
                  mode=['MC_Bs2JpsiPhi','MC_Bs2JpsiPhi_dG0','MC_Bd2JpsiKstar','Bd2JpsiKstar'],
                  branch=['B_P','B_PT','X_M'],
                  year=['2015','2016','2017','2018']),
    rwp2 = expand(rules.plot_angular_acceptance_reweightings.output,
                  version='{version}',
                  mode=['MC_Bs2JpsiPhi','MC_Bs2JpsiPhi_dG0'],
                  branch=['B_P','B_PT','X_M'],
                  angacc=['yearly'],
                  timeacc=['repo'],
                  weight=['sWeight','kinWeight','kkpWeight'],
                  year=['2015','2016','2017','2018']),
    # Time acceptance outputs
  output:
    "output/bundle/figures/{version}.zip"
  run:
    import os
    import shutil
    all_files = []
    for this_input in input:
      if isinstance(this_input, list):
        print('its a list')
        for item in this_input:
          all_files.append(item)
      else:
        all_files.append(this_input)

    print(all_files)
    print(output)
    cpath = f'{output}'
    cpath = os.path.abspath(os.path.dirname(cpath)) + f'/{wildcards.version}/'
    print(cpath)

    # Remove directory if it exists
    if os.path.isdir(f"{output[:-4]}"): os.system(f"rm -rf {output[:-4]}")

    # Loop over all input files and make a copy of all pdfs
    for file in all_files:
      if file.endswith('.pdf'):
        out_path = file.replace('output/figures/',cpath)
      else:
        out_path = None # add other methods if needed
      if out_path:
        print(f"Copying {file} to {out_path}...")
        os.system(f"mkdir -p {os.path.dirname(out_path)}") # create dir
        os.system(f"cp {file} {out_path}")                 # copy file
        #shutil.copy2(f"{file}", f"{file.replace('output/',out_path)}")
    try:
      print(f'{cpath}')
      shutil.make_archive(f'{cpath}','zip',f'{cpath}')
    except:
      print("Couldn't zip the contents")



"""
rule repository_bundle:
  wildcard_constraints:
    version = "(v[1-9]r[0-9]|v0r[2-9])"  # v0r0 and v0r2 (2015&2016) not allowed
  input:
    # Time acceptance outputs
    tap1 = expand(rules.decay_time_acceptance.output,
                  version='{version}',
                  year=['2015','2016','2017','2018'],
                  trigger=['biased','unbiased']),
    aap1 = expand(rules.iterativeRun2_angular_acceptance.output,
                  version='{version}'),
  output:
    "output/bundle/params/{version}.zip"
  run:
    import os
    import shutil
    all_files = []
    for this_input in input:
      if isinstance(this_input, list):
        print('its a list')
        for item in this_input:
          all_files.append(item)
      else:
        all_files.append(this_input)

    print(all_files)
    print(output)
    cpath = f'{output}'
    cpath = os.path.abspath(os.path.dirname(cpath)) + f'/{wildcards.version}/'
    print(cpath)

    # Remove directory if it exists
    if os.path.isdir(f"{output[:-4]}"): os.system(f"rm -rf {output[:-4]}")

    # Loop over all input files and make a copy of all pdfs
    for file in all_files:
      if file.endswith('.json'):
        out_path = file.replace('output/params/',cpath)
        out_path = out_path.replace('Bd2JpsiKstar','Bs2JpsiPhi')
      else:
        out_path = None # add other methods if needed
      if out_path:
        print(f"Copying {file} to {out_path}...")
        os.system(f"mkdir -p {os.path.dirname(out_path)}") # create dir
        os.system(f"cp {file} {out_path}")                 # copy file
        #shutil.copy2(f"{file}", f"{file.replace('output/',out_path)}")
    try:
      print(f'{cpath}')
      shutil.make_archive(f'{cpath}','zip',f'{cpath}')
    except:
      print("Couldn't zip the contents")
"""


rule translate_time_acceptance:
  input:
    biased = 'output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_Baseline_biased.json',
    unbiased = 'output/params/time_acceptance/{year}/Bd2JpsiKstar/{version}_Baseline_unbiased.json',
  output:
    'output/bundle/params/{version}/time_acceptance/{year}/time_acceptance_{year}.json'
  log:
    'output/log/bundle/translate_parameters/{version}/{year}/time_acceptance.json'
  run:
    shell(f"""(time\
    python bundle/pipeline_translation.py\
           --params-biased {input.biased}\
           --params-unbiased {input.unbiased}\
           --params-output {output}\
           --year {wildcards.year}\
           --version {wildcards.version}\
    ) &> {log} #2>&1""")

rule translate_angular_acceptance:
  input:
    biased = 'output/params/angular_acceptance/{year}/Bs2JpsiPhi/{version}_Baseline_biased.json',
    unbiased = 'output/params/angular_acceptance/{year}/Bs2JpsiPhi/{version}_Baseline_unbiased.json',
  output:
    'output/bundle/params/{version}/angular_acceptance/{year}/angular_acceptance_{year}.json'
  log:
    'output/log/bundle/translate_parameters/{version}/{year}/angular_acceptance.json'
  run:
    shell(f"""(time\
    python bundle/pipeline_translation.py\
           --params-biased {input.biased}\
           --params-unbiased {input.unbiased}\
           --params-output {output}\
           --year {wildcards.year}\
           --version {wildcards.version}\
    ) &> {log} #2>&1""")




rule share_acceptances:
  # wildcard_constraints:
  #   version = "(v[1-9]r[0-9]|v0r[2-9])"  # v0r0 and v0r2 (2015&2016) not allowed
  input:
    # Time acceptance outputs
    time = expand(rules.translate_time_acceptance.output,
                  version='{version}',year=[2015,2016]),
    angular = expand(rules.translate_angular_acceptance.output,
                     version='{version}',year=[2015,2016]),
  log:
    "output/log/bundle/share_acceptances/{version}.log"
  output:
    "output/bundle/params/{version}.zip"
  run:
    shell(f"""(time\
    python bundle/commit.py
    ) #&> {log} #2>&1""")
    cpath = f'{output}'
    try:
      import shutil
      shutil.make_archive(f'{cpath[:-4]}/','zip',f'{cpath[:-4]}/')
    except:
      print(f"Couldn't zip the contents from {cpath}")






rule compile_slides:
  input:
    rwp2 = expand(rules.plot_angular_acceptance_reweightings.output,
                  version=['v0r5'],
                  mode=['MC_Bs2JpsiPhi','MC_Bs2JpsiPhi_dG0'],
                  branch=['B_P','B_PT','X_M','hplus_PT','hplus_P','hminus_PT','hminus_P'],
                  angacc=['yearly'],
                  timeacc=['repo'],
                  weight=['sWeight','kinWeight','kkpWeight'],
                  year=['2015']),
                  #year=['2015','2016','2017','2018']),
  output:
    "output/bundle/main_{date}.pdf"
  log:
    'output/log/bundle/compile_slides/{date}.log'
  run:
    date = f"{wildcards.date}"
    import os
    if not os.path.isfile(f"bundle/tex/main_{date}.tex"):
      print(f"Creating main_{date}.tex from main.tex template")
      os.system(f"cp bundle/tex/main.tex bundle/tex/main_{date}.tex")
    shell(f"cd bundle/tex/; /home3/marcos.romero/.linuxbrew/Cellar/texlive/20200715/texlive/bin/x86_64-linux/latexmk -xelatex main_{date}.tex") #-silent
    shell(f"cp bundle/tex/main_{date}.tex output/bundle/main_{date}.pdf")
    shell(f"cd bundle/tex/; /home3/marcos.romero/.linuxbrew/Cellar/texlive/20200715/texlive/bin/x86_64-linux/latexmk -c main_{date}.tex")




# rule figures_bundle:
#   wildcard_constraints:
#     version = "(v[1-9]r[0-9]|v0r[2-9])"  # v0r0 and v0r2 (2015&2016) not allowed
#   input:
#     # Reweightings figures
#     rwp1 = expand(rules.plot_reweightings.output,
#                   version='{version}',
#                   mode=['MC_BsJpsiPhi','MC_BsJpsiPhi_dG0','MC_BdJpsiKstar,MC_BdJpsiKstar'],
#                   branch=['B_P','B_PT','X_M'],
#                   year=['2015','2016','2017','2018']),
#     # Time acceptance outputs
#     tap1 = expand(rules.decay_time_acceptance.output,
#                   version='{version}',
#                   year=['2015','2016','2017','2018'],
#                   trigger=['biased','unbiased'])#,
#     # time_acceptance_2 = expand(rules.decay_time_acceptance_without_kinweights.output,
#     #                            version='{version}',
#     #                            year=['2015','2016'],
#     #                            flag='test',
#     #                            trigger=['biased','unbiased'],
#     #                            script='nonkinweighted')
#   output:
#     zipfile = "output/bundle/figures/{version}.zip"
#   run:
#     import os
#     import shutil
#     all_files = []
#     for this_input in input:
#       if isinstance(this_input, list):
#         print('its a list')
#         for item in this_input:
#           all_files.append(item)
#       else:
#         all_files.append(this_input)
#
#     if os.path.isdir(f"{output.zipfile[:-4]}"):
#       os.system(f"rm -rf {output.zipfile[:-4]}")
#
#     for file in all_files:
#       if file.endswith('.pdf'):
#         out_path = f"{output.zipfile[:-4]}/figures/"
#         out_path = file.replace('figures/','').replace('output/',out_path)
#       elif file.endswith('.json'):
#         out_path = f"{output.zipfile[:-4]}/params/"
#         out_path = file.replace('params/','').replace('output/',out_path)
#       elif file.endswith('.tex'):
#         out_path = f"{output.zipfile[:-4]}/tables/"
#         out_path = file.replace('tables/','').replace('output/',out_path)
#       else:
#         out_path = None # add other methods if needed
#       if out_path:
#         print(f"Copying {file}...")
#         out_path = os.path.abspath(out_path)
#         os.system(f"mkdir -p {os.path.dirname(out_path)}") # create dir
#         os.system(f"cp {file} {out_path}")                 # copy file
#         #shutil.copy2(f"{file}", f"{file.replace('output/',out_path)}")
#       try:
#         shutil.make_archive(f'{output.zipfile[:-4]}','zip',f'{output.zipfile[:-4]}')
#       except:
#         print("Couldn't zip the contents")
