# sync_ntuples ----------------------------------------------------------------
#    This rule downloads all files corresponding to a given VERSION from EOS
#    to SAMPLES_PATH folder. It requires you to make a kinit on your system,
#    and then it worka automatically.

rule samples_sync_tuple:
  resources:
    mem_mb=4096
  output:
    # here I remove the temp for the sWeight file, in the future it will be added again
    sample = SAMPLES_PATH+'{year}/{mode}/{version}_sWeight.root'
  log:
    'output/log/samples_sync_tuple/{year}/{mode}/{version}.log'
  run:
    try:
      shell(f"""
        (time\
        python analysis/samples/sync_tuples.py\
               --year {wildcards.year}\
               --mode {wildcards.mode}\
               --version {wildcards.version}\
               --tree DecayTree\
               --output {output}\
        ) &> {log}""")
    except:
      print("These tuples are not yet avaliable at root://eoslhcb.cern.ch/*.",
      'You may need to create those tuples yourself or ask B2CC people to'
      'produce them')



# reduce_ntuples ---------------------------------------------------------------
#    Reduces the amount of branches in the original ntuples. This rule builds
#    the ntuples that will actually be used for phis-scq analysis package.

rule samples_reduce_tuple:
  resources:
    mem_mb=2048
  input:
    sample = lambda wcs: tuples(wcs, weight='kinWeight')
  output:
    sample = SAMPLES_PATH+'{year}/{mode}/{version,[A-Za-z0-9]+}.root'
  log:
    'output/log/samples_reduce_tuple/{year}/{mode}/{version}.log'
  run:
    shell(f"""(time\
    python analysis/samples/reduce_tuples.py\
           --input-file {input.sample}\
           --output-file {output.sample}\
           --input-tree DecayTree\
           --output-tree DecayTree\
    ) &> {log}""")
