# reweightings -----------------------------------------------------------------
#    Reduces the amount of branches in the original ntuples. This rule builds
#    the ntuples that will actually be used for phis-scq analysis package. .split('_')[1],



# polarity weighting -----------------------------------------------------------
#    Adds polWeight to MC tuples matching the corresponding data sample. This
#    rule runs only over MC tuples.
rule reweighting_polarity:
  wildcard_constraints:
    mode = "MC_(Bs2JpsiPhi|Bd2JpsiKstar)(_dG0)?"
  input:
    original = lambda wcs: tuples(wcs,weight='sWeight'),
    target   = lambda wcs: tuples(wcs,mode='Bs2JpsiPhi',weight='sWeight'),
  output:
    sample   = temp(SAMPLES_PATH+'{year}/{mode}/{version}_polWeight.root')
  log:
    'output/log/reweightings/polarity_weighting/{year}/{mode}/{version}.log'
  run:
    shell(f"""(time\
          python reweightings/polarity_weighting.py\
                 --original-file {input.original}\
                 --original-treename DecayTree\
                 --target-file {input.target}\
                 --target-treename DecayTree\
                 --output-file {output.sample}
    ) &> {log} #2>&1""")
    send_mail(f"Polarity weighting", f"{log}")



# p.d.f. weighting -------------------------------------------------------------
#    Adds pdfWeight to MC tuples matching the corresponding data sample. This
#    rule runs only over MC tuples.
rule reweighting_pdf:
  wildcard_constraints:
    mode = "MC_(Bs2JpsiPhi|Bd2JpsiKstar)(_dG0)?"
  input:
    sample = lambda wcs: tuples(wcs,weight='polWeight'),
  params:
    original = lambda wcs: f"{wcs.year}/{wcs.mode[3:].split('_')[0]}.json",
    target = lambda wcs: f"{wcs.year}/{wcs.mode}.json",
  output:
    sample = temp(SAMPLES_PATH+'{year}/{mode}/{version}_pdfWeight.root')
  log:
    'output/log/reweightings/pdf_weighting/{year}/{mode}/{version}.log'
  run:
    shell(f"""(time\
      python reweightings/pdf_weighting.py\
             --input-file {input.sample}\
             --tree-name DecayTree\
             --output-file {output.sample}\
             --target-params reweightings/parameters/{params.target}\
             --original-params reweightings/parameters/{params.original}\
             --mode {wildcards.mode}
    ) &> {log} #2>&1""")
    send_mail(f"P.D.F. weighting", f"{log}")



# kinematic weighting ----------------------------------------------------------
#    Adds kinWeight to MC_BsJpsiPhi*, MC_BdJpsiKstar and Bd2JpsiKstar tuples
#    gb-weighting them to match kinematic distributions of their complementary
#    sample.
rule reweighting_kinematic:
  wildcard_constraints:
    mode = "(MC_(Bs2JpsiPhi|Bd2JpsiKstar)(_dG0|_Swave)?|Bd2JpsiKstar)"
  input:
    original = lambda wcs: tuples(wcs,weight='pdfWeight'),
    target = lambda wcs: tuples(wcs,mode='cdata',weight='kinWeight'),
  output:
    sample = temp(SAMPLES_PATH+'{year}/{mode}/{version}_kinWeight.root')
  log:
    'output/log/reweightings/kinematic_weighting/{year}/{mode}/{version}.log'
  run:
    import os
    import hjson
    bdconfig = hjson.load(open('config.json'))['time_acceptance_bdtconfig']
    year = f'{wildcards.year}'
    mode = f'{wildcards.mode}'
    version = f'{wildcards.version}'
    end  = 'selected_bdt_sw'
    if mode.startswith('MC_Bs2JpsiPhi'):
      shell(f"""(time\
        python reweightings/kinematic_weighting.py\
          --original-file {input.original}\
          --original-treename DecayTree\
          --original-vars "B_PT X_M" \
          --original-weight "(sw/gb_weights)*polWeight*pdfWeight"\
          --target-file {input.target}\
          --target-treename DecayTree\
          --target-vars "B_PT X_M"\
          --target-weight "sw"\
          --output-file {output.sample}\
          --n-estimators {bdconfig['n_estimators']}\
          --learning-rate {bdconfig['learning_rate']}\
          --max-depth {bdconfig['max_depth']}\
          --min-samples-leaf {bdconfig['min_samples_leaf']}
      ) &> {log} #2>&1""")
    elif mode.startswith('MC_Bd2JpsiKstar'):
      shell(f"""(time\
        python reweightings/kinematic_weighting.py\
          --original-file {input.original}\
          --original-treename DecayTree\
          --original-vars "B_PT X_M" \
          --original-weight "sw*polWeight*pdfWeight"\
          --target-file {input.target}\
          --target-treename DecayTree\
          --target-vars "B_PT X_M"\
          --target-weight "sw*kinWeight"\
          --output-file {output.sample}\
          --n-estimators {bdconfig['n_estimators']}\
          --learning-rate {bdconfig['learning_rate']}\
          --max-depth {bdconfig['max_depth']}\
          --min-samples-leaf {bdconfig['min_samples_leaf']}
      ) &> {log} #2>&1""")
    elif mode.startswith('Bd2JpsiKstar'):
      shell(f"""(time\
        python reweightings/kinematic_weighting.py\
          --original-file {input.original}\
          --original-treename DecayTree\
          --original-vars "B_PT B_P" \
          --original-weight "sw"\
          --target-file {input.target}\
          --target-treename DecayTree\
          --target-vars "B_PT B_P"\
          --target-weight "sw"\
          --output-file {output.sample}\
          --n-estimators {bdconfig['n_estimators']}\
          --learning-rate {bdconfig['learning_rate']}\
          --max-depth {bdconfig['max_depth']}\
          --min-samples-leaf {bdconfig['min_samples_leaf']}
      ) &> {log} #2>&1""")
    else:
      shell(f"""(time\
        cp {input.original} {output.sample}
      ) &> {log} #2>&1""")
    send_mail(f"Kinematic weighting", f"{log}")




# reweighting plots ------------------------------------------------------------
#    Adds polWeight to MC tuples matching the corresponding data sample. This
#    rule runs only over MC tuples.

rule reweightings_plot_time_acceptance:
  wildcard_constraints:
    branch = "((B|hplus|hminus)_P(T)?|X_M)",
    weight = "(s|kin|kkp)Weight"
  input:
    original = lambda wcs: tuples(wcs),
    target = lambda wcs: tuples(wcs,mode='cdata')
  output:
    sweighted = 'output/figures/reweightings/{year}/{mode}/{version,[A-Za-z0-9]+}_{branch}_sWeight.pdf',
    kinweighted = 'output/figures/reweightings/{year}/{mode}/{version}_{branch}_kinWeight.pdf',
  log:
    'output/log/reweightings/plot_time_reweightings/{year}/{mode}/{version}_{branch}.log',
  run:
    shell(f"""(time\
    python reweightings/reweighting_plots.py\
           --original {input.original}\
           --target {input.target}\
           --year {wildcards.year}\
           --mode {wildcards.mode}\
           --version {wildcards.version}\
           --branch {wildcards.branch}\
           --sweighted {output.sweighted}\
           --kinweighted {output.kinweighted}\
    ) &> {log} #2>&1""")
    send_mail(f"Polarity weighting", f"{log}", f"{output}".split(' '))


rule reweightings_plot_angular_acceptance:
  wildcard_constraints:
    mode = "(TOY|MC)_Bs2JpsiPhi(_dG0)?",
    branch = "((B|hplus|hminus)_P(T)?|X_M)",
    weight = "(s|kin|kkp)Weight"
  input:
    original = lambda wcs: tuples(wcs),
    weights = lambda wcs: tuples(wcs,weight='angWeight'),
    target = lambda wcs: tuples(wcs,mode='cdata')
  output:
    'output/figures/reweightings/{year}/{mode}/{version,[A-Za-z0-9]+}_{branch}_{angacc}_{timeacc}_{weight}.pdf',
  log:
    'output/log/reweightings/plot_angular_reweightings/{year}/{mode}/{version}_{branch}_{angacc}_{timeacc}_{weight}.log',
  run:
    shell(f"""(time\
    python angular_acceptance/plot1.py\
           --original {input.original}\
           --weights {input.weights}\
           --target {input.target}\
           --year {wildcards.year}\
           --mode {wildcards.mode}\
           --version {wildcards.version}\
           --branch {wildcards.branch}\
           --treename {wildcards.angacc}_{wildcards.timeacc}\
           --kkpweighted {output}\
    ) &> {log} #2>&1""")
    send_mail(f"Polarity weighting", f"{output}")              # WARNING #



rule reweightings_simon_comparisons:
  input:
    original = lambda wcs: tuples(wcs),
    target = lambda wcs: tuples(wcs,mode='cdata')
  output:
    'output/figures/reweightings/{year}/{mode}/{version,[A-Za-z0-9]+}_{branch}_comparison.pdf',
  log:
    'output/log/reweightings/simon_comparisons/{year}/{mode}/{version}_{branch}.log',
  run:
    shell(f"""(time\
    python reweightings/reweighting_plots.py\
           --original {input.original}\
           --target {input.target}\
           --year {wildcards.year}\
           --mode {wildcards.mode}\
           --version {wildcards.version}\
           --branch {wildcards.branch}\
           --sweighted {output.sweighted}\
           --kinweighted {output.kinweighted}\
    ) &> {log} #2>&1""")
